# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rpc-demo-gw.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'rpc-demo-gw.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11rpc-demo-gw.proto\x12\nRPCDemoPkg\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\" \n\nMultCoords\x12\x12\n\x06values\x18\x01 \x03(\x01\x42\x02\x10\x01\"\x19\n\tImageData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\xd3\x01\n\x07RPCDemo\x12j\n\rGetMultCoords\x12\x16.google.protobuf.Empty\x1a\x16.RPCDemoPkg.MultCoords\")\x82\xd3\xe4\x93\x02#\"\x1e/restgatewaydemo/getmultcoords:\x01*\x12\\\n\x08GetImage\x12\x16.google.protobuf.Empty\x1a\x15.RPCDemoPkg.ImageData\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/restgatewaydemo/getimageB&Z$example.com/rest-gateway-demo/protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_demo_gw_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$example.com/rest-gateway-demo/protos'
  _globals['_MULTCOORDS'].fields_by_name['values']._loaded_options = None
  _globals['_MULTCOORDS'].fields_by_name['values']._serialized_options = b'\020\001'
  _globals['_RPCDEMO'].methods_by_name['GetMultCoords']._loaded_options = None
  _globals['_RPCDEMO'].methods_by_name['GetMultCoords']._serialized_options = b'\202\323\344\223\002#\"\036/restgatewaydemo/getmultcoords:\001*'
  _globals['_RPCDEMO'].methods_by_name['GetImage']._loaded_options = None
  _globals['_RPCDEMO'].methods_by_name['GetImage']._serialized_options = b'\202\323\344\223\002\033\022\031/restgatewaydemo/getimage'
  _globals['_MULTCOORDS']._serialized_start=92
  _globals['_MULTCOORDS']._serialized_end=124
  _globals['_IMAGEDATA']._serialized_start=126
  _globals['_IMAGEDATA']._serialized_end=151
  _globals['_RPCDEMO']._serialized_start=154
  _globals['_RPCDEMO']._serialized_end=365
# @@protoc_insertion_point(module_scope)
